hexo:icarus:
  stage: build
  trigger:
    include: .meta/pipeline/site-gen/hexo/icarus/build.gitlab-ci.yml
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
      - "site-gen/hexo/icarus/Dockerfile"
      - "site-gen/hexo/icarus/goss.yaml"
      - "site-gen/hexo/icarus/tusk.yml"
      when: on_success
    - if: '$TRIGGER_VAR1 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "hexo" && $TRIGGER_VAR2 == "icarus"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "hexo" && $TRIGGER_VAR2 == "all"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success