runner:latest:
  stage: build
  trigger:
    include: .meta/pipeline/misc/runner/build.gitlab-ci.yml
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
        - "misc/runner/Dockerfile"
        - "misc/runner/goss.yaml"
        - "misc/runner/tusk.yml"
      when: on_success
    - if: '$TRIGGER_VAR1 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "runner" && $TRIGGER_VAR2 == "latest"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "runner" && $TRIGGER_VAR2 == "all"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success
