hugo:hello-friend:
  stage: build
  trigger:
    include: .meta/pipeline/site-gen/hugo/hello-friend/build.gitlab-ci.yml
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
      - "site-gen/hugo/hello-friend/Dockerfile"
      - "site-gen/hugo/hello-friend/goss.yaml"
      - "site-gen/hugo/hello-friend/tusk.yml"
      when: on_success
    - if: '$TRIGGER_VAR1 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "hugo" && $TRIGGER_VAR2 == "hello-friend"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "hugo" && $TRIGGER_VAR2 == "all"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success